name: Actualizar GeoJSON Transporte La Plata

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Actualizado a v5 para soporte de entornos modernos
      - name: Clonar el repositorio
        uses: actions/checkout@v5

      # Actualizado a v6 para soporte de entornos modernos
      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Ejecutar script de extracción
        run: python script_transporte.py

      - name: Hacer Commit y Push del archivo GeoJSON actualizado
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add transporte_la_plata.geojson
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update: GeoJSON transporte" && git push)

          - name: Hacer Commit y Push del archivo GeoJSON actualizado
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [ -f transporte_la_plata.geojson ]; then
            git add transporte_la_plata.geojson
            git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update: GeoJSON transporte" && git push)
          else
            echo "El archivo transporte_la_plata.geojson no fue generado."
      
