name: Actualizar GeoJSON Transporte La Plata

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # PASO NUEVO: Instalar requests
      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script de extracción
        run: python script_transporte.py

      - name: Hacer Commit y Push del archivo GeoJSON actualizado
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [ -f transporte_la_plata.geojson ]; then
            git add transporte_la_plata.geojson
            git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update: GeoJSON transporte" && git push)
          fi
